"""``rm-validate init`` — infer capabilities and write a commented policy.

Runs once per repo. It infers capabilities from the real code (with evidence),
suggests a profile, and writes an ``rm-policy.yaml`` whose every capability line
carries the evidence that set it. It configures; it does not validate.

It deliberately does NOT propose ``layering_patterns`` (folder conventions are
too risky to guess). If a layering fitness function ends up enabled without its
patterns, that is surfaced as pending in the console summary — never
auto-completed.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from rm_validate.checks.registry import CAPABILITY, FITNESS, all_specs
from rm_validate.config import DEFAULT_EXCLUDE_GLOBS
from rm_validate.inference import InferenceResult, infer
from rm_validate.profiles import ALL_CAPABILITIES

POLICY_FILENAME = "rm-policy.yaml"
# Fitness functions safe to enable without any declared layers.
_LAYERLESS_FITNESS = ("no_circular_dependencies",)


@dataclass
class InitResult:
    written_to: Path | None
    yaml_text: str
    summary: str


def run_init(repo: Path, *, force: bool = False, write: bool = True) -> InitResult:
    inferred = infer(repo, list(DEFAULT_EXCLUDE_GLOBS))
    profile = inferred.suggested_profile()
    yaml_text = _render_policy(repo.name, profile, inferred)

    target = repo / POLICY_FILENAME
    written_to: Path | None = None
    if write:
        if target.exists() and not force:
            summary = _summary(repo, profile, inferred, wrote=False, exists=True)
            return InitResult(written_to=None, yaml_text=yaml_text, summary=summary)
        target.write_text(yaml_text, encoding="utf-8")
        written_to = target

    summary = _summary(repo, profile, inferred, wrote=write, exists=target.exists())
    return InitResult(written_to=written_to, yaml_text=yaml_text, summary=summary)


def _render_policy(project: str, profile: str, inferred: InferenceResult) -> str:
    lines: list[str] = []
    lines.append("# rm-policy.yaml — generated by `rm-validate init`.")
    lines.append("# Capabilities were inferred from the code (evidence in comments below).")
    lines.append("# Confirm the profile with an ADR, then run `rm-validate check`.")
    lines.append("")
    lines.append('version: "0.1.0"')
    lines.append(f'project: "{project}"')
    lines.append("")
    lines.append(f"extends: {profile}          # suggested from detected capabilities")
    lines.append("capabilities:")
    for cap in ALL_CAPABILITIES:
        ev = inferred.capabilities[cap]
        value = "true" if ev.detected else "false"
        note = "; ".join(ev.evidence) if ev.evidence else "no evidence found"
        lines.append(f"  {cap}: {value}    # {note}")
    lines.append("")
    lines.append("enforcement:")
    lines.append('  mode: "warning"                 # switch to "blocking" once stable')
    lines.append("  require_profile_adr: true       # add ADR/0001-perfil-*.md, then check passes")
    lines.append("  capability_mismatch_fails: true")
    lines.append("  baseline_ratchet:")
    lines.append("    enabled: false                # set true to adopt on a legacy repo")
    lines.append('    baseline_file: ".rm/baseline.json"')
    lines.append("    block_only_new_violations: true")
    lines.append("")
    lines.append("modularity:")
    lines.append("  code_file_lines: { soft: 300, hard: 500 }")
    lines.append("  context_file_lines: { hard: 500 }")
    lines.append("")
    lines.append("fitness_functions:")
    lines.append("  no_circular_dependencies: true")
    lines.append("  # Layering checks below need layering_patterns declared by hand:")
    lines.append("  domain_must_not_import_infrastructure: false")
    lines.append("  ui_must_not_access_db_directly: false")
    lines.append("  engines_must_be_pure: false")
    lines.append("  mutations_server_side_only: false")
    lines.append("")
    lines.append("# To enable a layering check, set it true AND declare its globs, e.g.:")
    lines.append("# layering_patterns:")
    lines.append('#   domain: ["app/domain/**"]')
    lines.append('#   infrastructure: ["app/infra*/**", "app/adapters/**"]')
    lines.append("")
    lines.append("prompt_gate:")
    lines.append("  required_sections: []           # list your prompt-contract sections to gate")
    lines.append("  paths: []                       # e.g. ['prompts/**/*.md']")
    lines.append("")
    lines.append("security:")
    lines.append("  no_secrets_in_repo: true")
    lines.append("  dependency_scan_in_ci: true")
    lines.append("")
    return "\n".join(lines)


def _summary(
    repo: Path, profile: str, inferred: InferenceResult, *, wrote: bool, exists: bool
) -> str:
    out: list[str] = []
    out.append(f"rm-validate init — {repo.name}")
    out.append("")
    out.append(f"suggested profile: {profile}")
    out.append("")
    out.append("detected capabilities:")
    for cap in ALL_CAPABILITIES:
        ev = inferred.capabilities[cap]
        if ev.detected:
            out.append(f"  + {cap}: {'; '.join(ev.evidence)}")
    if not any(ev.detected for ev in inferred.capabilities.values()):
        out.append("  (none — static profile territory)")
    out.append("")
    out.append("checks that would activate:")
    caps = inferred.detected()
    for spec in all_specs():
        if spec.kind == CAPABILITY and not caps.get(spec.requires_capability or ""):
            continue
        if spec.kind == FITNESS and spec.fitness_function not in _LAYERLESS_FITNESS:
            continue
        out.append(f"  - {spec.name}: {spec.summary}")
    out.append("")
    out.append("pending (manual):")
    out.append("  - confirm the profile with an ADR (enforcement.require_profile_adr).")
    out.append("  - declare layering_patterns before enabling any layering fitness function.")
    out.append("")
    if wrote:
        out.append(f"wrote {POLICY_FILENAME}")
    elif exists:
        out.append(f"{POLICY_FILENAME} already exists — not overwritten (use --force). "
                   "Generated content printed above.")
    return "\n".join(out)
